[.text-justify]
= Szablon README
:reproducible:
:doctype: article
:author: Herman Ciechanowiec
:email: herman@ciechanowiec.eu
:chapter-signifier:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:toc: left
:toclevels: 5
:icons: font
:docinfo: shared,private
:linkcss:
:sourcedir: {docdir}
:pdf-theme: {sourcedir}/.docs/themes/basic.yml
:pdf-fontsdir: {sourcedir}/.docs/themes/fonts,GEM_FONTS_DIR
:stylesdir: https://www.ciechanowiec.eu/linux_mantra/
:stylesheet: adoc-css-style.css
:!table-caption:
:!figure-caption:
:!example-caption:

[cols=">.^1,<.^1"]
|===
| *Ostatnia modyfikacja dokumentu:* | {docdatetime}
| *Data wygenerowania dokumentu:* | {localdatetime}
|===

== O dokumencie

Tekst źródłowy niniejszego dokumentu wykorzystuje język znaczników https://asciidoc.org[AsciiDoc^]. Wytyczne, eksport i sprawdzanie pisowni opisane poniżej znajdują się w repozytorium przechowującym tekst źródłowy, a wyeksportowana kopia dokumentu nie zawiera żadnego z tych elementów.

=== Wytyczne

Tekst źródłowy powinien być zgodny z link:README-guideline-writing.adoc[wytycznymi pisania], przechowywanymi obok niego w repozytorium.

=== Wymagane narzędzia

Aby eksportować i sprawdzać tekst źródłowy, należy zainstalować następujące narzędzia:

. https://asciidoctor.org/#installation[Asciidoctor^]
. https://docs.asciidoctor.org/pdf-converter/latest/install/[Asciidoctor PDF^]
. https://pandoc.org/installing.html[Pandoc^]
. https://www.python.org/downloads/[Python 3^]
. https://vale.sh/docs/install/[Vale^]
. https://poppler.freedesktop.org[`pdftotext`^]
. https://github.com/tesseract-ocr/tesseract[`tesseract`^]

=== Eksport

. Eksport tekstu źródłowego do HTML:
+
[source,bash,subs="attributes+"]
----
asciidoctor --attribute allow-uri-read {docname}{docfilesuffix}
----

. Eksport tekstu źródłowego do PDF:
+
[source,bash,subs="attributes+"]
----
asciidoctor-pdf --attribute allow-uri-read --require ./.docs/lib/common-style.rb {docname}{docfilesuffix}
----

. Eksport tekstu źródłowego do DOCX:
+
[source,bash,subs="attributes+"]
----
prepared="$(python3 {sourcedir}/.docs/lib/export_prepare.py --docx-compat {docname}{docfilesuffix})" && asciidoctor --backend docbook --attribute allow-uri-read --out-file - "$prepared" | pandoc --from docbook --to docx --reference-doc={sourcedir}/.docs/themes/reference.docx --output {docname}.docx && python3 {sourcedir}/.docs/lib/apply_docx_formatting.py {docname}.docx && rm "$prepared"
----

=== Sprawdzanie pisowni

Sprawdzanie tekstu źródłowego:

[source,bash,subs="attributes+"]
----
python3 .docs/lib/adoc_lint.py {docname}{docfilesuffix}
----
